<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AF', 'phone_code' => '+93', 'flag' => 'af.png', 'currency_name' => 'Afghan Afghani', 'currency_code' => 'AFN', 'currency_symbol' => '؋'],
            ['name' => 'Albania', 'code' => 'AL', 'phone_code' => '+355', 'flag' => 'al.png', 'currency_name' => 'Albanian Lek', 'currency_code' => 'ALL', 'currency_symbol' => 'L'],
            ['name' => 'Algeria', 'code' => 'DZ', 'phone_code' => '+213', 'flag' => 'dz.png', 'currency_name' => 'Algerian Dinar', 'currency_code' => 'DZD', 'currency_symbol' => 'دج'],
            ['name' => 'Andorra', 'code' => 'AD', 'phone_code' => '+376', 'flag' => 'ad.png', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Angola', 'code' => 'AO', 'phone_code' => '+244', 'flag' => 'ao.png', 'currency_name' => 'Angolan Kwanza', 'currency_code' => 'AOA', 'currency_symbol' => 'Kz'],
            ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'phone_code' => '+1-268', 'flag' => 'ag.png', 'currency_name' => 'East Caribbean Dollar', 'currency_code' => 'XCD', 'currency_symbol' => '$'],
            ['name' => 'Argentina', 'code' => 'AR', 'phone_code' => '+54', 'flag' => 'ar.png', 'currency_name' => 'Argentine Peso', 'currency_code' => 'ARS', 'currency_symbol' => '$'],
            ['name' => 'Armenia', 'code' => 'AM', 'phone_code' => '+374', 'flag' => 'am.png', 'currency_name' => 'Armenian Dram', 'currency_code' => 'AMD', 'currency_symbol' => '֏'],
            ['name' => 'Australia', 'code' => 'AU', 'phone_code' => '+61', 'flag' => 'au.png', 'currency_name' => 'Australian Dollar', 'currency_code' => 'AUD', 'currency_symbol' => '$'],
            ['name' => 'Austria', 'code' => 'AT', 'phone_code' => '+43', 'flag' => 'at.png', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'phone_code' => '+994', 'flag' => 'az.png', 'currency_name' => 'Azerbaijani Manat', 'currency_code' => 'AZN', 'currency_symbol' => '₼'],
            ['name' => 'Bahamas', 'code' => 'BS', 'phone_code' => '+1-242', 'flag' => 'bs.png', 'currency_name' => 'Bahamian Dollar', 'currency_code' => 'BSD', 'currency_symbol' => '$'],
            ['name' => 'Bahrain', 'code' => 'BH', 'phone_code' => '+973', 'flag' => 'bh.png', 'currency_name' => 'Bahraini Dinar', 'currency_code' => 'BHD', 'currency_symbol' => '.د.ب'],
            ['name' => 'Bangladesh', 'code' => 'BD', 'phone_code' => '+880', 'flag' => 'bd.png', 'currency_name' => 'Bangladeshi Taka', 'currency_code' => 'BDT', 'currency_symbol' => '৳'],
            ['name' => 'Barbados', 'code' => 'BB', 'phone_code' => '+1-246', 'flag' => 'bb.png', 'currency_name' => 'Barbadian Dollar', 'currency_code' => 'BBD', 'currency_symbol' => '$'],
            ['name' => 'Belarus', 'code' => 'BY', 'phone_code' => '+375', 'flag' => 'by.png', 'currency_name' => 'Belarusian Ruble', 'currency_code' => 'BYN', 'currency_symbol' => 'Br'],
            ['name' => 'Belgium', 'code' => 'BE', 'phone_code' => '+32', 'flag' => 'be.png', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Belize', 'code' => 'BZ', 'phone_code' => '+501', 'flag' => 'bz.png', 'currency_name' => 'Belize Dollar', 'currency_code' => 'BZD', 'currency_symbol' => 'BZ$'],
            ['name' => 'Benin', 'code' => 'BJ', 'phone_code' => '+229', 'flag' => 'bj.png', 'currency_name' => 'West African CFA franc', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA'],
            ['name' => 'Bhutan', 'code' => 'BT', 'phone_code' => '+975', 'flag' => 'bt.png', 'currency_name' => 'Bhutanese Ngultrum', 'currency_code' => 'BTN', 'currency_symbol' => 'Nu.'],
            ['name' => 'Bolivia', 'code' => 'BO', 'phone_code' => '+591', 'flag' => 'bo.png', 'currency_name' => 'Bolivian Boliviano', 'currency_code' => 'BOB', 'currency_symbol' => 'Bs.'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'phone_code' => '+387', 'flag' => 'ba.png', 'currency_name' => 'Bosnia and Herzegovina Convertible Mark', 'currency_code' => 'BAM', 'currency_symbol' => 'KM'],
            ['name' => 'Botswana', 'code' => 'BW', 'phone_code' => '+267', 'flag' => 'bw.png', 'currency_name' => 'Botswana Pula', 'currency_code' => 'BWP', 'currency_symbol' => 'P'],
            ['name' => 'Brazil', 'code' => 'BR', 'phone_code' => '+55', 'flag' => 'br.png', 'currency_name' => 'Brazilian Real', 'currency_code' => 'BRL', 'currency_symbol' => 'R$'],
            ['name' => 'Brunei Darussalam', 'code' => 'BN', 'phone_code' => '+673', 'flag' => 'bn.png', 'currency_name' => 'Brunei Dollar', 'currency_code' => 'BND', 'currency_symbol' => '$'],
            ['name' => 'Bulgaria', 'code' => 'BG', 'phone_code' => '+359', 'flag' => 'bg.png', 'currency_name' => 'Bulgarian Lev', 'currency_code' => 'BGN', 'currency_symbol' => 'лв'],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'phone_code' => '+226', 'flag' => 'bf.png', 'currency_name' => 'West African CFA franc', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA'],
            ['name' => 'Burundi', 'code' => 'BI', 'phone_code' => '+257', 'flag' => 'bi.png', 'currency_name' => 'Burundian Franc', 'currency_code' => 'BIF', 'currency_symbol' => 'FBu'],
            ['name' => 'Cambodia', 'code' => 'KH', 'phone_code' => '+855', 'flag' => 'kh.png', 'currency_name' => 'Cambodian Riel', 'currency_code' => 'KHR', 'currency_symbol' => '៛'],
            ['name' => 'Cameroon', 'code' => 'CM', 'phone_code' => '+237', 'flag' => 'cm.png', 'currency_name' => 'Central African CFA franc', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA'],
            ['name' => 'Canada', 'code' => 'CA', 'phone_code' => '+1', 'flag' => 'ca.png', 'currency_name' => 'Canadian Dollar', 'currency_code' => 'CAD', 'currency_symbol' => '$'],
            ['name' => 'Cape Verde', 'code' => 'CV', 'phone_code' => '+238', 'flag' => 'cv.png', 'currency_name' => 'Cape Verdean Escudo', 'currency_code' => 'CVE', 'currency_symbol' => 'Esc'],
            ['name' => 'Central African Republic', 'code' => 'CF', 'phone_code' => '+236', 'flag' => 'cf.png', 'currency_name' => 'Central African CFA franc', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA'],
            ['name' => 'Chad', 'code' => 'TD', 'phone_code' => '+235', 'flag' => 'td.png', 'currency_name' => 'Central African CFA franc', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA'],
            ['name' => 'Chile', 'code' => 'CL', 'phone_code' => '+56', 'flag' => 'cl.png', 'currency_name' => 'Chilean Peso', 'currency_code' => 'CLP', 'currency_symbol' => '$'],
            ['name' => 'China', 'code' => 'CN', 'phone_code' => '+86', 'flag' => 'cn.png', 'currency_name' => 'Chinese Yuan', 'currency_code' => 'CNY', 'currency_symbol' => '¥'],
            ['name' => 'Colombia', 'code' => 'CO', 'phone_code' => '+57', 'flag' => 'co.png', 'currency_name' => 'Colombian Peso', 'currency_code' => 'COP', 'currency_symbol' => '$'],
            ['name' => 'Comoros', 'code' => 'KM', 'phone_code' => '+269', 'flag' => 'km.png', 'currency_name' => 'Comorian Franc', 'currency_code' => 'KMF', 'currency_symbol' => 'CF'],
            ['name' => 'Congo (Brazzaville)', 'code' => 'CG', 'phone_code' => '+242', 'flag' => 'cg.png', 'currency_name' => 'Central African CFA franc', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA'],
            ['name' => 'Congo (Kinshasa)', 'code' => 'CD', 'phone_code' => '+243', 'flag' => 'cd.png', 'currency_name' => 'Congolese Franc', 'currency_code' => 'CDF', 'currency_symbol' => 'FC'],
            ['name' => 'Costa Rica', 'code' => 'CR', 'phone_code' => '+506', 'flag' => 'cr.png', 'currency_name' => 'Costa Rican Colón', 'currency_code' => 'CRC', 'currency_symbol' => '₡'],
            ['name' => 'Croatia', 'code' => 'HR', 'phone_code' => '+385', 'flag' => 'hr.png', 'currency_name' => 'Croatian Kuna', 'currency_code' => 'HRK', 'currency_symbol' => 'kn'],
            ['name' => 'Cuba', 'code' => 'CU', 'phone_code' => '+53', 'flag' => 'cu.png', 'currency_name' => 'Cuban Peso', 'currency_code' => 'CUP', 'currency_symbol' => '$'],
            ['name' => 'Cyprus', 'code' => 'CY', 'phone_code' => '+357', 'flag' => 'cy.png', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Czech Republic', 'code' => 'CZ', 'phone_code' => '+420', 'flag' => 'cz.png', 'currency_name' => 'Czech Koruna', 'currency_code' => 'CZK', 'currency_symbol' => 'Kč'],
            ['name' => 'Denmark', 'code' => 'DK', 'phone_code' => '+45', 'flag' => 'dk.png', 'currency_name' => 'Danish Krone', 'currency_code' => 'DKK', 'currency_symbol' => 'kr'],
            ['name' => 'Djibouti', 'code' => 'DJ', 'phone_code' => '+253', 'flag' => 'dj.png', 'currency_name' => 'Djiboutian Franc', 'currency_code' => 'DJF', 'currency_symbol' => 'Fdj'],
            ['name' => 'Dominica', 'code' => 'DM', 'phone_code' => '+1-767', 'flag' => 'dm.png', 'currency_name' => 'East Caribbean Dollar', 'currency_code' => 'XCD', 'currency_symbol' => '$'],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'phone_code' => '+1-809', 'flag' => 'do.png', 'currency_name' => 'Dominican Peso', 'currency_code' => 'DOP', 'currency_symbol' => 'RD$'],
            ['name' => 'Ecuador', 'code' => 'EC', 'phone_code' => '+593', 'flag' => 'ec.png', 'currency_name' => 'United States Dollar', 'currency_code' => 'USD', 'currency_symbol' => '$'],
            ['name' => 'Egypt', 'code' => 'EG', 'phone_code' => '+20', 'flag' => 'eg.png', 'currency_name' => 'Egyptian Pound', 'currency_code' => 'EGP', 'currency_symbol' => '£'],
            ['name' => 'El Salvador', 'code' => 'SV', 'phone_code' => '+503', 'flag' => 'sv.png', 'currency_name' => 'United States Dollar', 'currency_code' => 'USD', 'currency_symbol' => '$'],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'phone_code' => '+240', 'flag' => 'gq.png', 'currency_name' => 'Central African CFA franc', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA'],
            ['name' => 'Eritrea', 'code' => 'ER', 'phone_code' => '+291', 'flag' => 'er.png', 'currency_name' => 'Eritrean Nakfa', 'currency_code' => 'ERN', 'currency_symbol' => 'Nfk'],
            ['name' => 'Estonia', 'code' => 'EE', 'phone_code' => '+372', 'flag' => 'ee.png', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Eswatini', 'code' => 'SZ', 'phone_code' => '+268', 'flag' => 'sz.png', 'currency_name' => 'Swazi Lilangeni', 'currency_code' => 'SZL', 'currency_symbol' => 'E'],
            ['name' => 'Ethiopia', 'code' => 'ET', 'phone_code' => '+251', 'flag' => 'et.png', 'currency_name' => 'Ethiopian Birr', 'currency_code' => 'ETB', 'currency_symbol' => 'Br'],
            ['name' => 'Fiji', 'code' => 'FJ', 'phone_code' => '+679', 'flag' => 'fj.png', 'currency_name' => 'Fijian Dollar', 'currency_code' => 'FJD', 'currency_symbol' => '$'],
            ['name' => 'Finland', 'code' => 'FI', 'phone_code' => '+358', 'flag' => 'fi.png', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'France', 'code' => 'FR', 'phone_code' => '+33', 'flag' => 'fr.png', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Gabon', 'code' => 'GA', 'phone_code' => '+241', 'flag' => 'ga.png', 'currency_name' => 'Central African CFA franc', 'currency_code' => 'XAF', 'currency_symbol' => 'FCFA'],
            ['name' => 'Gambia', 'code' => 'GM', 'phone_code' => '+220', 'flag' => 'gm.png', 'currency_name' => 'Gambian Dalasi', 'currency_code' => 'GMD', 'currency_symbol' => 'D'],
            ['name' => 'Georgia', 'code' => 'GE', 'phone_code' => '+995', 'flag' => 'ge.png', 'currency_name' => 'Georgian Lari', 'currency_code' => 'GEL', 'currency_symbol' => '₾'],
            ['name' => 'Germany', 'code' => 'DE', 'phone_code' => '+49', 'flag' => 'de.png', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Ghana', 'code' => 'GH', 'phone_code' => '+233', 'flag' => 'gh.png', 'currency_name' => 'Ghanaian Cedi', 'currency_code' => 'GHS', 'currency_symbol' => '₵'],
            ['name' => 'Greece', 'code' => 'GR', 'phone_code' => '+30', 'flag' => 'gr.png', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Grenada', 'code' => 'GD', 'phone_code' => '+1-473', 'flag' => 'gd.png', 'currency_name' => 'East Caribbean Dollar', 'currency_code' => 'XCD', 'currency_symbol' => '$'],
            ['name' => 'Guatemala', 'code' => 'GT', 'phone_code' => '+502', 'flag' => 'gt.png', 'currency_name' => 'Guatemalan Quetzal', 'currency_code' => 'GTQ', 'currency_symbol' => 'Q'],
            ['name' => 'Guinea', 'code' => 'GN', 'phone_code' => '+224', 'flag' => 'gn.png', 'currency_name' => 'Guinean Franc', 'currency_code' => 'GNF', 'currency_symbol' => 'FG'],
            ['name' => 'Guinea-Bissau', 'code' => 'GW', 'phone_code' => '+245', 'flag' => 'gw.png', 'currency_name' => 'West African CFA franc', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA'],
            ['name' => 'Guyana', 'code' => 'GY', 'phone_code' => '+592', 'flag' => 'gy.png', 'currency_name' => 'Guyanese Dollar', 'currency_code' => 'GYD', 'currency_symbol' => '$'],
            ['name' => 'Haiti', 'code' => 'HT', 'phone_code' => '+509', 'flag' => 'ht.png', 'currency_name' => 'Haitian Gourde', 'currency_code' => 'HTG', 'currency_symbol' => 'G'],
            ['name' => 'Honduras', 'code' => 'HN', 'phone_code' => '+504', 'flag' => 'hn.png', 'currency_name' => 'Honduran Lempira', 'currency_code' => 'HNL', 'currency_symbol' => 'L'],
            ['name' => 'Hungary', 'code' => 'HU', 'phone_code' => '+36', 'flag' => 'hu.png', 'currency_name' => 'Hungarian Forint', 'currency_code' => 'HUF', 'currency_symbol' => 'Ft'],
            ['name' => 'Iceland', 'code' => 'IS', 'phone_code' => '+354', 'flag' => 'is.png', 'currency_name' => 'Icelandic Króna', 'currency_code' => 'ISK', 'currency_symbol' => 'kr'],
            ['name' => 'India', 'code' => 'IN', 'phone_code' => '+91', 'flag' => 'in.png', 'currency_name' => 'Indian Rupee', 'currency_code' => 'INR', 'currency_symbol' => '₹'],
            ['name' => 'Indonesia', 'code' => 'ID', 'phone_code' => '+62', 'flag' => 'id.png', 'currency_name' => 'Indonesian Rupiah', 'currency_code' => 'IDR', 'currency_symbol' => 'Rp'],
            ['name' => 'Iran', 'code' => 'IR', 'phone_code' => '+98', 'flag' => 'ir.png', 'currency_name' => 'Iranian Rial', 'currency_code' => 'IRR', 'currency_symbol' => '﷼'],
            ['name' => 'Iraq', 'code' => 'IQ', 'phone_code' => '+964', 'flag' => 'iq.png', 'currency_name' => 'Iraqi Dinar', 'currency_code' => 'IQD', 'currency_symbol' => 'ع.د'],
            ['name' => 'Ireland', 'code' => 'IE', 'phone_code' => '+353', 'flag' => 'ie.png', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Israel', 'code' => 'IL', 'phone_code' => '+972', 'flag' => 'il.png', 'currency_name' => 'Israeli New Shekel', 'currency_code' => 'ILS', 'currency_symbol' => '₪'],
            ['name' => 'Italy', 'code' => 'IT', 'phone_code' => '+39', 'flag' => 'it.png', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Jamaica', 'code' => 'JM', 'phone_code' => '+1-876', 'flag' => 'jm.png', 'currency_name' => 'Jamaican Dollar', 'currency_code' => 'JMD', 'currency_symbol' => '$'],
            ['name' => 'Japan', 'code' => 'JP', 'phone_code' => '+81', 'flag' => 'jp.png', 'currency_name' => 'Japanese Yen', 'currency_code' => 'JPY', 'currency_symbol' => '¥'],
            ['name' => 'Jordan', 'code' => 'JO', 'phone_code' => '+962', 'flag' => 'jo.png', 'currency_name' => 'Jordanian Dinar', 'currency_code' => 'JOD', 'currency_symbol' => 'JD'],
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'phone_code' => '+7', 'flag' => 'kz.png', 'currency_name' => 'Kazakhstani Tenge', 'currency_code' => 'KZT', 'currency_symbol' => '₸'],
            ['name' => 'Kenya', 'code' => 'KE', 'phone_code' => '+254', 'flag' => 'ke.png', 'currency_name' => 'Kenyan Shilling', 'currency_code' => 'KES', 'currency_symbol' => 'KSh'],
            ['name' => 'Kiribati', 'code' => 'KI', 'phone_code' => '+686', 'flag' => 'ki.png', 'currency_name' => 'Australian Dollar', 'currency_code' => 'AUD', 'currency_symbol' => '$'],
            ['name' => 'Kuwait', 'code' => 'KW', 'phone_code' => '+965', 'flag' => 'kw.png', 'currency_name' => 'Kuwaiti Dinar', 'currency_code' => 'KWD', 'currency_symbol' => 'د.ك'],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'phone_code' => '+996', 'flag' => 'kg.png', 'currency_name' => 'Kyrgyzstani Som', 'currency_code' => 'KGS', 'currency_symbol' => 'с'],
            ['name' => 'Laos', 'code' => 'LA', 'phone_code' => '+856', 'flag' => 'la.png', 'currency_name' => 'Lao Kip', 'currency_code' => 'LAK', 'currency_symbol' => '₭'],
            ['name' => 'Latvia', 'code' => 'LV', 'phone_code' => '+371', 'flag' => 'lv.png', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Lebanon', 'code' => 'LB', 'phone_code' => '+961', 'flag' => 'lb.png', 'currency_name' => 'Lebanese Pound', 'currency_code' => 'LBP', 'currency_symbol' => '£'],
            ['name' => 'Lesotho', 'code' => 'LS', 'phone_code' => '+266', 'flag' => 'ls.png', 'currency_name' => 'Lesotho Loti', 'currency_code' => 'LSL', 'currency_symbol' => 'L'],
            ['name' => 'Liberia', 'code' => 'LR', 'phone_code' => '+231', 'flag' => 'lr.png', 'currency_name' => 'Liberian Dollar', 'currency_code' => 'LRD', 'currency_symbol' => '$'],
            ['name' => 'Libya', 'code' => 'LY', 'phone_code' => '+218', 'flag' => 'ly.png', 'currency_name' => 'Libyan Dinar', 'currency_code' => 'LYD', 'currency_symbol' => 'ل.د'],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'phone_code' => '+423', 'flag' => 'li.png', 'currency_name' => 'Swiss Franc', 'currency_code' => 'CHF', 'currency_symbol' => 'Fr'],
            ['name' => 'Lithuania', 'code' => 'LT', 'phone_code' => '+370', 'flag' => 'lt.png', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Luxembourg', 'code' => 'LU', 'phone_code' => '+352', 'flag' => 'lu.png', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Madagascar', 'code' => 'MG', 'phone_code' => '+261', 'flag' => 'mg.png', 'currency_name' => 'Malagasy Ariary', 'currency_code' => 'MGA', 'currency_symbol' => 'Ar'],
            ['name' => 'Malawi', 'code' => 'MW', 'phone_code' => '+265', 'flag' => 'mw.png', 'currency_name' => 'Malawian Kwacha', 'currency_code' => 'MWK', 'currency_symbol' => 'MK'],
            ['name' => 'Malaysia', 'code' => 'MY', 'phone_code' => '+60', 'flag' => 'my.png', 'currency_name' => 'Malaysian Ringgit', 'currency_code' => 'MYR', 'currency_symbol' => 'RM'],
            ['name' => 'Maldives', 'code' => 'MV', 'phone_code' => '+960', 'flag' => 'mv.png', 'currency_name' => 'Maldivian Rufiyaa', 'currency_code' => 'MVR', 'currency_symbol' => 'Rf'],
            ['name' => 'Mali', 'code' => 'ML', 'phone_code' => '+223', 'flag' => 'ml.png', 'currency_name' => 'West African CFA franc', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA'],
            ['name' => 'Malta', 'code' => 'MT', 'phone_code' => '+356', 'flag' => 'mt.png', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Marshall Islands', 'code' => 'MH', 'phone_code' => '+692', 'flag' => 'mh.png', 'currency_name' => 'United States Dollar', 'currency_code' => 'USD', 'currency_symbol' => '$'],
            ['name' => 'Mauritania', 'code' => 'MR', 'phone_code' => '+222', 'flag' => 'mr.png', 'currency_name' => 'Mauritanian Ouguiya', 'currency_code' => 'MRU', 'currency_symbol' => 'UM'],
            ['name' => 'Mauritius', 'code' => 'MU', 'phone_code' => '+230', 'flag' => 'mu.png', 'currency_name' => 'Mauritian Rupee', 'currency_code' => 'MUR', 'currency_symbol' => '₨'],
            ['name' => 'Mexico', 'code' => 'MX', 'phone_code' => '+52', 'flag' => 'mx.png', 'currency_name' => 'Mexican Peso', 'currency_code' => 'MXN', 'currency_symbol' => '$'],
            ['name' => 'Micronesia', 'code' => 'FM', 'phone_code' => '+691', 'flag' => 'fm.png', 'currency_name' => 'United States Dollar', 'currency_code' => 'USD', 'currency_symbol' => '$'],
            ['name' => 'Moldova', 'code' => 'MD', 'phone_code' => '+373', 'flag' => 'md.png', 'currency_name' => 'Moldovan Leu', 'currency_code' => 'MDL', 'currency_symbol' => 'L'],
            ['name' => 'Monaco', 'code' => 'MC', 'phone_code' => '+377', 'flag' => 'mc.png', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Mongolia', 'code' => 'MN', 'phone_code' => '+976', 'flag' => 'mn.png', 'currency_name' => 'Mongolian Tögrög', 'currency_code' => 'MNT', 'currency_symbol' => '₮'],
            ['name' => 'Montenegro', 'code' => 'ME', 'phone_code' => '+382', 'flag' => 'me.png', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Morocco', 'code' => 'MA', 'phone_code' => '+212', 'flag' => 'ma.png', 'currency_name' => 'Moroccan Dirham', 'currency_code' => 'MAD', 'currency_symbol' => 'د.م.'],
            ['name' => 'Mozambique', 'code' => 'MZ', 'phone_code' => '+258', 'flag' => 'mz.png', 'currency_name' => 'Mozambican Metical', 'currency_code' => 'MZN', 'currency_symbol' => 'MT'],
            ['name' => 'Myanmar', 'code' => 'MM', 'phone_code' => '+95', 'flag' => 'mm.png', 'currency_name' => 'Burmese Kyat', 'currency_code' => 'MMK', 'currency_symbol' => 'K'],
            ['name' => 'Namibia', 'code' => 'NA', 'phone_code' => '+264', 'flag' => 'na.png', 'currency_name' => 'Namibian Dollar', 'currency_code' => 'NAD', 'currency_symbol' => '$'],
            ['name' => 'Nauru', 'code' => 'NR', 'phone_code' => '+674', 'flag' => 'nr.png', 'currency_name' => 'Australian Dollar', 'currency_code' => 'AUD', 'currency_symbol' => '$'],
            ['name' => 'Nepal', 'code' => 'NP', 'phone_code' => '+977', 'flag' => 'np.png', 'currency_name' => 'Nepalese Rupee', 'currency_code' => 'NPR', 'currency_symbol' => '₨'],
            ['name' => 'Netherlands', 'code' => 'NL', 'phone_code' => '+31', 'flag' => 'nl.png', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'New Zealand', 'code' => 'NZ', 'phone_code' => '+64', 'flag' => 'nz.png', 'currency_name' => 'New Zealand Dollar', 'currency_code' => 'NZD', 'currency_symbol' => '$'],
            ['name' => 'Nicaragua', 'code' => 'NI', 'phone_code' => '+505', 'flag' => 'ni.png', 'currency_name' => 'Nicaraguan Córdoba', 'currency_code' => 'NIO', 'currency_symbol' => 'C$'],
            ['name' => 'Niger', 'code' => 'NE', 'phone_code' => '+227', 'flag' => 'ne.png', 'currency_name' => 'West African CFA franc', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA'],
            ['name' => 'Nigeria', 'code' => 'NG', 'phone_code' => '+234', 'flag' => 'ng.png', 'currency_name' => 'Nigerian Naira', 'currency_code' => 'NGN', 'currency_symbol' => '₦'],
            ['name' => 'North Korea', 'code' => 'KP', 'phone_code' => '+850', 'flag' => 'kp.png', 'currency_name' => 'North Korean Won', 'currency_code' => 'KPW', 'currency_symbol' => '₩'],
            ['name' => 'North Macedonia', 'code' => 'MK', 'phone_code' => '+389', 'flag' => 'mk.png', 'currency_name' => 'Macedonian Denar', 'currency_code' => 'MKD', 'currency_symbol' => 'ден'],
            ['name' => 'Norway', 'code' => 'NO', 'phone_code' => '+47', 'flag' => 'no.png', 'currency_name' => 'Norwegian Krone', 'currency_code' => 'NOK', 'currency_symbol' => 'kr'],
            ['name' => 'Oman', 'code' => 'OM', 'phone_code' => '+968', 'flag' => 'om.png', 'currency_name' => 'Omani Rial', 'currency_code' => 'OMR', 'currency_symbol' => 'ر.ع.'],
            ['name' => 'Pakistan', 'code' => 'PK', 'phone_code' => '+92', 'flag' => 'pk.png', 'currency_name' => 'Pakistani Rupee', 'currency_code' => 'PKR', 'currency_symbol' => '₨'],
            ['name' => 'Palau', 'code' => 'PW', 'phone_code' => '+680', 'flag' => 'pw.png', 'currency_name' => 'United States Dollar', 'currency_code' => 'USD', 'currency_symbol' => '$'],
            ['name' => 'Palestine', 'code' => 'PS', 'phone_code' => '+970', 'flag' => 'ps.png', 'currency_name' => 'Israeli New Shekel', 'currency_code' => 'ILS', 'currency_symbol' => '₪'],
            ['name' => 'Panama', 'code' => 'PA', 'phone_code' => '+507', 'flag' => 'pa.png', 'currency_name' => 'Panamanian Balboa', 'currency_code' => 'PAB', 'currency_symbol' => 'B/.'],
            ['name' => 'Papua New Guinea', 'code' => 'PG', 'phone_code' => '+675', 'flag' => 'pg.png', 'currency_name' => 'Papua New Guinean Kina', 'currency_code' => 'PGK', 'currency_symbol' => 'K'],
            ['name' => 'Paraguay', 'code' => 'PY', 'phone_code' => '+595', 'flag' => 'py.png', 'currency_name' => 'Paraguayan Guaraní', 'currency_code' => 'PYG', 'currency_symbol' => '₲'],
            ['name' => 'Peru', 'code' => 'PE', 'phone_code' => '+51', 'flag' => 'pe.png', 'currency_name' => 'Peruvian Sol', 'currency_code' => 'PEN', 'currency_symbol' => 'S/.'],
            ['name' => 'Philippines', 'code' => 'PH', 'phone_code' => '+63', 'flag' => 'ph.png', 'currency_name' => 'Philippine Peso', 'currency_code' => 'PHP', 'currency_symbol' => '₱'],
            ['name' => 'Poland', 'code' => 'PL', 'phone_code' => '+48', 'flag' => 'pl.png', 'currency_name' => 'Polish Złoty', 'currency_code' => 'PLN', 'currency_symbol' => 'zł'],
            ['name' => 'Portugal', 'code' => 'PT', 'phone_code' => '+351', 'flag' => 'pt.png', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Qatar', 'code' => 'QA', 'phone_code' => '+974', 'flag' => 'qa.png', 'currency_name' => 'Qatari Riyal', 'currency_code' => 'QAR', 'currency_symbol' => 'ر.ق'],
            ['name' => 'Romania', 'code' => 'RO', 'phone_code' => '+40', 'flag' => 'ro.png', 'currency_name' => 'Romanian Leu', 'currency_code' => 'RON', 'currency_symbol' => 'L'],
            ['name' => 'Russia', 'code' => 'RU', 'phone_code' => '+7', 'flag' => 'ru.png', 'currency_name' => 'Russian Ruble', 'currency_code' => 'RUB', 'currency_symbol' => '₽'],
            ['name' => 'Rwanda', 'code' => 'RW', 'phone_code' => '+250', 'flag' => 'rw.png', 'currency_name' => 'Rwandan Franc', 'currency_code' => 'RWF', 'currency_symbol' => 'FRw'],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'phone_code' => '+1-869', 'flag' => 'kn.png', 'currency_name' => 'East Caribbean Dollar', 'currency_code' => 'XCD', 'currency_symbol' => '$'],
            ['name' => 'Saint Lucia', 'code' => 'LC', 'phone_code' => '+1-758', 'flag' => 'lc.png', 'currency_name' => 'East Caribbean Dollar', 'currency_code' => 'XCD', 'currency_symbol' => '$'],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'phone_code' => '+1-784', 'flag' => 'vc.png', 'currency_name' => 'East Caribbean Dollar', 'currency_code' => 'XCD', 'currency_symbol' => '$'],
            ['name' => 'Samoa', 'code' => 'WS', 'phone_code' => '+685', 'flag' => 'ws.png', 'currency_name' => 'Samoan tālā', 'currency_code' => 'WST', 'currency_symbol' => 'T'],
            ['name' => 'San Marino', 'code' => 'SM', 'phone_code' => '+378', 'flag' => 'sm.png', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Sao Tome and Principe', 'code' => 'ST', 'phone_code' => '+239', 'flag' => 'st.png', 'currency_name' => 'São Tomé and Príncipe Dobra', 'currency_code' => 'STN', 'currency_symbol' => 'Db'],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'phone_code' => '+966', 'flag' => 'sa.png', 'currency_name' => 'Saudi Riyal', 'currency_code' => 'SAR', 'currency_symbol' => 'ر.س'],
            ['name' => 'Senegal', 'code' => 'SN', 'phone_code' => '+221', 'flag' => 'sn.png', 'currency_name' => 'West African CFA franc', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA'],
            ['name' => 'Serbia', 'code' => 'RS', 'phone_code' => '+381', 'flag' => 'rs.png', 'currency_name' => 'Serbian Dinar', 'currency_code' => 'RSD', 'currency_symbol' => 'дин'],
            ['name' => 'Seychelles', 'code' => 'SC', 'phone_code' => '+248', 'flag' => 'sc.png', 'currency_name' => 'Seychellois Rupee', 'currency_code' => 'SCR', 'currency_symbol' => '₨'],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'phone_code' => '+232', 'flag' => 'sl.png', 'currency_name' => 'Sierra Leonean Leone', 'currency_code' => 'SLL', 'currency_symbol' => 'Le'],
            ['name' => 'Singapore', 'code' => 'SG', 'phone_code' => '+65', 'flag' => 'sg.png', 'currency_name' => 'Singapore Dollar', 'currency_code' => 'SGD', 'currency_symbol' => '$'],
            ['name' => 'Slovakia', 'code' => 'SK', 'phone_code' => '+421', 'flag' => 'sk.png', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Slovenia', 'code' => 'SI', 'phone_code' => '+386', 'flag' => 'si.png', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Solomon Islands', 'code' => 'SB', 'phone_code' => '+677', 'flag' => 'sb.png', 'currency_name' => 'Solomon Islands Dollar', 'currency_code' => 'SBD', 'currency_symbol' => '$'],
            ['name' => 'Somalia', 'code' => 'SO', 'phone_code' => '+252', 'flag' => 'so.png', 'currency_name' => 'Somali Shilling', 'currency_code' => 'SOS', 'currency_symbol' => 'Sh'],
            ['name' => 'South Africa', 'code' => 'ZA', 'phone_code' => '+27', 'flag' => 'za.png', 'currency_name' => 'South African Rand', 'currency_code' => 'ZAR', 'currency_symbol' => 'R'],
            ['name' => 'South Korea', 'code' => 'KR', 'phone_code' => '+82', 'flag' => 'kr.png', 'currency_name' => 'South Korean Won', 'currency_code' => 'KRW', 'currency_symbol' => '₩'],
            ['name' => 'South Sudan', 'code' => 'SS', 'phone_code' => '+211', 'flag' => 'ss.png', 'currency_name' => 'South Sudanese Pound', 'currency_code' => 'SSP', 'currency_symbol' => '£'],
            ['name' => 'Spain', 'code' => 'ES', 'phone_code' => '+34', 'flag' => 'es.png', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'phone_code' => '+94', 'flag' => 'lk.png', 'currency_name' => 'Sri Lankan Rupee', 'currency_code' => 'LKR', 'currency_symbol' => '₨'],
            ['name' => 'Sudan', 'code' => 'SD', 'phone_code' => '+249', 'flag' => 'sd.png', 'currency_name' => 'Sudanese Pound', 'currency_code' => 'SDG', 'currency_symbol' => '£'],
            ['name' => 'Suriname', 'code' => 'SR', 'phone_code' => '+597', 'flag' => 'sr.png', 'currency_name' => 'Surinamese Dollar', 'currency_code' => 'SRD', 'currency_symbol' => '$'],
            ['name' => 'Sweden', 'code' => 'SE', 'phone_code' => '+46', 'flag' => 'se.png', 'currency_name' => 'Swedish Krona', 'currency_code' => 'SEK', 'currency_symbol' => 'kr'],
            ['name' => 'Switzerland', 'code' => 'CH', 'phone_code' => '+41', 'flag' => 'ch.png', 'currency_name' => 'Swiss Franc', 'currency_code' => 'CHF', 'currency_symbol' => 'Fr'],
            ['name' => 'Syria', 'code' => 'SY', 'phone_code' => '+963', 'flag' => 'sy.png', 'currency_name' => 'Syrian Pound', 'currency_code' => 'SYP', 'currency_symbol' => '£'],
            ['name' => 'Taiwan', 'code' => 'TW', 'phone_code' => '+886', 'flag' => 'tw.png', 'currency_name' => 'New Taiwan Dollar', 'currency_code' => 'TWD', 'currency_symbol' => 'NT$'],
            ['name' => 'Tajikistan', 'code' => 'TJ', 'phone_code' => '+992', 'flag' => 'tj.png', 'currency_name' => 'Tajikistani Somoni', 'currency_code' => 'TJS', 'currency_symbol' => 'ЅМ'],
            ['name' => 'Tanzania', 'code' => 'TZ', 'phone_code' => '+255', 'flag' => 'tz.png', 'currency_name' => 'Tanzanian Shilling', 'currency_code' => 'TZS', 'currency_symbol' => 'Sh'],
            ['name' => 'Thailand', 'code' => 'TH', 'phone_code' => '+66', 'flag' =>'th.png', 'currency_name' => 'Thai Baht', 'currency_code' => 'THB', 'currency_symbol' => '฿'],
            ['name' => 'Togo', 'code' => 'TG', 'phone_code' => '+228', 'flag' => 'tg.png', 'currency_name' => 'West African CFA franc', 'currency_code' => 'XOF', 'currency_symbol' => 'CFA'],
            ['name' => 'Tonga', 'code' => 'TO', 'phone_code' => '+676', 'flag' => 'to.png', 'currency_name' => 'Tongan paʻanga', 'currency_code' => 'TOP', 'currency_symbol' => 'T$'],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'phone_code' => '+1-868', 'flag' => 'tt.png', 'currency_name' => 'Trinidad and Tobago Dollar', 'currency_code' => 'TTD', 'currency_symbol' => '$'],
            ['name' => 'Tunisia', 'code' => 'TN', 'phone_code' => '+216', 'flag' => 'tn.png', 'currency_name' => 'Tunisian Dinar', 'currency_code' => 'TND', 'currency_symbol' => 'د.ت'],
            ['name' => 'Turkey', 'code' => 'TR', 'phone_code' => '+90', 'flag' => 'tr.png', 'currency_name' => 'Turkish Lira', 'currency_code' => 'TRY', 'currency_symbol' => '₺'],
            ['name' => 'Turkmenistan', 'code' => 'TM', 'phone_code' => '+993', 'flag' => 'tm.png', 'currency_name' => 'Turkmenistan Manat', 'currency_code' => 'TMT', 'currency_symbol' => 'm'],
            ['name' => 'Tuvalu', 'code' => 'TV', 'phone_code' => '+688', 'flag' => 'tv.png', 'currency_name' => 'Australian Dollar', 'currency_code' => 'AUD', 'currency_symbol' => '$'],
            ['name' => 'Uganda', 'code' => 'UG', 'phone_code' => '+256', 'flag' => 'ug.png', 'currency_name' => 'Ugandan Shilling', 'currency_code' => 'UGX', 'currency_symbol' => 'USh'],
            ['name' => 'Ukraine', 'code' => 'UA', 'phone_code' => '+380', 'flag' => 'ua.png', 'currency_name' => 'Ukrainian Hryvnia', 'currency_code' => 'UAH', 'currency_symbol' => '₴'],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'phone_code' => '+971', 'flag' => 'ae.png', 'currency_name' => 'United Arab Emirates dirham', 'currency_code' => 'AED', 'currency_symbol' => 'د.إ'],
            ['name' => 'United Kingdom', 'code' => 'GB', 'phone_code' => '+44', 'flag' => 'gb.png', 'currency_name' => 'British Pound Sterling', 'currency_code' => 'GBP', 'currency_symbol' => '£'],
            ['name' => 'United States', 'code' => 'US', 'phone_code' => '+1', 'flag' => 'us.png', 'currency_name' => 'United States Dollar', 'currency_code' => 'USD', 'currency_symbol' => '$'],
            ['name' => 'Uruguay', 'code' => 'UY', 'phone_code' => '+598', 'flag' => 'uy.png', 'currency_name' => 'Uruguayan Peso', 'currency_code' => 'UYU', 'currency_symbol' => '$U'],
            ['name' => 'Uzbekistan', 'code' => 'UZ', 'phone_code' => '+998', 'flag' => 'uz.png', 'currency_name' => 'Uzbekistani Som', 'currency_code' => 'UZS', 'currency_symbol' => 'soʻm'],
            ['name' => 'Vanuatu', 'code' => 'VU', 'phone_code' => '+678', 'flag' => 'vu.png', 'currency_name' => 'Vanuatu Vatu', 'currency_code' => 'VUV', 'currency_symbol' => 'VT'],
            ['name' => 'Vatican City', 'code' => 'VA', 'phone_code' => '+379', 'flag' => 'va.png', 'currency_name' => 'Euro', 'currency_code' => 'EUR', 'currency_symbol' => '€'],
            ['name' => 'Venezuela', 'code' => 'VE', 'phone_code' => '+58', 'flag' => 've.png', 'currency_name' => 'Venezuelan bolívar', 'currency_code' => 'VES', 'currency_symbol' => 'Bs.S'],
            ['name' => 'Vietnam', 'code' => 'VN', 'phone_code' => '+84', 'flag' => 'vn.png', 'currency_name' => 'Vietnamese đồng', 'currency_code' => 'VND', 'currency_symbol' => '₫'],
            ['name' => 'Yemen', 'code' => 'YE', 'phone_code' => '+967', 'flag' => 'ye.png', 'currency_name' => 'Yemeni Rial', 'currency_code' => 'YER', 'currency_symbol' => '﷼'],
            ['name' => 'Zambia', 'code' => 'ZM', 'phone_code' => '+260', 'flag' => 'zm.png', 'currency_name' => 'Zambian Kwacha', 'currency_code' => 'ZMW', 'currency_symbol' => 'ZK'],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'phone_code' => '+263', 'flag' => 'zw.png', 'currency_name' => 'Zimbabwean Dollar', 'currency_code' => 'ZWL', 'currency_symbol' => '$']
        ];
        foreach ($countries as $country) {
            DB::table('countries')->insert(
                array_merge(['id' => Str::uuid(),'created_at'=>now(),'updated_at'=>now()], $country)
            );
        }
    }
}
